CREATE TRIGGER Sync ON DATABASE FOR ALTER_TABLE AS
BEGIN
    DECLARE @XML_RESULT XML
    DECLARE @OBJECT_TYPE NVARCHAR(50)
    DECLARE @OBJECT_NAME NVARCHAR(50)

    SET @XML_RESULT = EVENTDATA()
    SET @OBJECT_TYPE = @XML_RESULT.value('(/EVENT_INSTANCE/ObjectType)[1]', 'nvarchar(50)')

    IF @OBJECT_TYPE = 'TABLE'
    BEGIN
        SET @OBJECT_NAME = @XML_RESULT.value('(/EVENT_INSTANCE/ObjectName)[1]', 'nvarchar(50)')
        EXEC dbo.Sync_RefreshElements @OBJECT_NAME
    END
END
GO
DISABLE TRIGGER Sync ON DATABASE