//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalData
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new ObservableCollection<Order>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Region { get; set; }
    
        public virtual ObservableCollection<Order> Orders { get; set; }
    }
}
