//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalData
{

    public partial class Order
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string Item { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
